---

# Travis file for CI & automated remote testing of roles

dist: trusty
sudo: required

services:
  - docker

language: ruby
rvm:
  - 2.1.5

env:
    - ANSIBLE_ROLES_PATH="${TRAVIS_BUILD_DIR%/*/*}"
    
before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

  # Install necessary deps for crypto
  - sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip language-pack-en

  # Install Ansible and various deps.
  - >
    sudo pip install markupsafe cryptography paramiko PyYAML Jinja2 httplib2 six ansible ansible-lint

install:

  # Add ansible.cfg to pick up roles path.
  - "cp ./tests/ansible.cfg ./"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory playbooks/provision.yml --syntax-check

  # Run linter on role
  - ansible-lint playbooks/provision.yml

  # Run the role/playbook with ansible-playbook.
  - >
    ansible-playbook -i tests/inventory playbooks/provision.yml
    --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory playbooks/provision.yml
    --connection=local --sudo
    | grep -q 'changed=[0].*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
