---
- name: Add NodeSource deb repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
    state: present

- name: Install Node.js
  apt:
    pkg:
      - nodejs=4*
    state: installed
    update_cache: yes
    force: yes

- name: Install Grunt-cli
  npm: name="grunt-cli" global=yes

- name: Install Gulp-cli
  npm: name="gulp-cli" global=yes

- name: Install Npm-cache
  npm: name="npm-cache" global=yes

- name: Install Bower
  npm: name="bower" global=yes

- name: Install Yeoman
  npm: name="yo" global=yes

- name: Fix npm umask
  command: sudo npm config set umask 0002 --global
  tags:
    - skip_ansible_lint

- name: Create npm-cache directory
  file: path=/srv/npm-cache/ state=directory owner=www-data group=www-data mode=0777

- name: Set npm-cache environment variable
  lineinfile: dest='/etc/environment' line='NPM_CACHE_DIR="/srv/npm-cache/"' state=present

